<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8" />';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge" />';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0" />';
echo '<link rel="stylesheet" href="./styles/style.css" />';
echo '<link rel="preconnect" href="https://fonts.googleapis.com" />';
echo '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />';
echo '<link';
echo 'href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap"';
echo 'rel="stylesheet"';
echo '/>';
echo '<title>Corona Form</title>';
echo '</head>';
echo '<body>';
echo '<fieldset>';
echo '<legend>Corona Form</legend>';
echo '<form action="./php/AddData.php" method="post">';
echo '<label for="fname">First name:</label>';
echo '<input type="text" id="fname" name="fname" placeholder="John" /><br />';
echo '<label for="lname">Last name:</label>';
echo '<input';
echo 'type="text"';
echo 'id="lname"';
echo 'name="lname"';
echo 'placeholder="Doe"';
echo '/><br /><br />';
echo '<label for="addres">Address:</label>';
echo '<input';
echo 'type="text"';
echo 'id="adress"';
echo 'name="adress"';
echo 'placeholder="Street, Str.Number, City"';
echo '/><br /><br />';
echo '<label for="date">Date:</label>';
echo '<input type="date" id="date" name="date" /><br /><br />';
echo '<label for="time">Time:</label>';
echo '<input type="time" id="time" name="time" /><br /><br />';
echo '<input type="reset" placeholder="reset" name="reset" />';
echo '<input type="submit" placeholder="Submit" name="submit" />';
echo '</form>';
echo '</fieldset>';
echo '<script src="./JavaScript/app.js"></script>';
echo '</body>';
echo '</html>';
echo '';
?>